---
abstract: "fast check if point is inside polygon\r"
author:
  - 'liosha <liosha@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Polygon-Tree
requires:
  Carp: 0
  Exporter: 0
  List::MoreUtils: 0
  List::Util: 0
  Math::Geometry::Planar::GPC::Polygon: 0
  POSIX: 0
  base: 0
  perl: 5.010
  strict: 0
  utf8: 0
  warnings: 0
version: 0.061
