--- #YAML:1.0
name:               Math-Polygon-Tree
version:            0.041
abstract:           Class for fast check if point is inside polygon
author:
    - liosha <liosha@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    List::MoreUtils:      0
    List::Util:           0
    Math::Geometry::Planar::GPC::Polygon:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
